// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8oyHFtXciDG91gIxLFt7-u61V_uGk4b0',
    appId: '1:764901754693:web:a12c838393f5e31401a02c',
    messagingSenderId: '764901754693',
    projectId: 'smart-lobster-oase-pps',
    authDomain: 'smart-lobster-oase-pps.firebaseapp.com',
    databaseURL: 'https://smart-lobster-oase-pps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lobster-oase-pps.firebasestorage.app',
    measurementId: 'G-S49F96KPD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAxfgUB8cZsSBkphBQ3nUZnz0Kx6DUh8',
    appId: '1:764901754693:android:1708087cbdf4d42601a02c',
    messagingSenderId: '764901754693',
    projectId: 'smart-lobster-oase-pps',
    databaseURL: 'https://smart-lobster-oase-pps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lobster-oase-pps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyO8HB1tfNpwsYDiRM80S1GHAWsBRyik',
    appId: '1:764901754693:ios:c7e8ca8f75ba6be601a02c',
    messagingSenderId: '764901754693',
    projectId: 'smart-lobster-oase-pps',
    databaseURL: 'https://smart-lobster-oase-pps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lobster-oase-pps.firebasestorage.app',
    iosBundleId: 'com.example.smartLobsterMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyO8HB1tfNpwsYDiRM80S1GHAWsBRyik',
    appId: '1:764901754693:ios:c7e8ca8f75ba6be601a02c',
    messagingSenderId: '764901754693',
    projectId: 'smart-lobster-oase-pps',
    databaseURL: 'https://smart-lobster-oase-pps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lobster-oase-pps.firebasestorage.app',
    iosBundleId: 'com.example.smartLobsterMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8oyHFtXciDG91gIxLFt7-u61V_uGk4b0',
    appId: '1:764901754693:web:48b4b932d7e710b501a02c',
    messagingSenderId: '764901754693',
    projectId: 'smart-lobster-oase-pps',
    authDomain: 'smart-lobster-oase-pps.firebaseapp.com',
    databaseURL: 'https://smart-lobster-oase-pps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-lobster-oase-pps.firebasestorage.app',
    measurementId: 'G-JR8PEPTJ0H',
  );
}
